name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  screenshot: ^2.1.0
  image_picker: ^1.0.7
  build_runner: ^2.4.7
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  share_plus: ^7.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  freezed: ^2.4.6

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true